apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: digitalocean-k8s
  namespace: default
spec:
  interval: 5m
  url: https://github.com/dorjanshurdhi/digitalocean-k8s.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: digitalocean-k8s
  namespace: default
spec:
  interval: 10m
  targetNamespace: default
  sourceRef:
    kind: GitRepository
    name: digitalocean-k8s
  path: "./kubernetes/manifest/overlays/devops"
  prune: true
