---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: devops
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./kubernetes/manifest/overlays/devops
  prune: true
  sourceRef:
    kind: GitRepository
    name: digitalocean-k8s
  targetNamespace: default

