apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  #call base folder
- ../../base
  #call flux folder
- ./flux

namespace: my-app-dev

nameSuffix: -dev

patchesStrategicMerge:
- deployment_env.yaml


configMapGenerator:
  - name: app-config
    literals:
      - username=demo-user

secretGenerator:
  - name: credentials
    type: Opaque
    literals:
      - password=demo
